<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        //【  4 5 】
        //1 7 3 2 4 5

        // 同步代码
        // p2 暂存 p4暂存
        // [p1,p3,p4,p2]
        new Promise((resolve, reject) => {
                resolve()
                //此时执行 把p1推入到微队列中 promise2在主线程中执行 resolve 把p3推入到微队列中
                //主线程没有代码 执行微队列中的 p1执行打印1 执行b里面的resolve 然后 把p4推到微队列中 
                //p4仅仅被推入队列中并没有执行，所以p5不会进入队列，所以相当于p1调用完成，p2推入到微队列中
                //执行p3 （7）主线程代码执行完毕  执行微队列中的p4（3）
                //执行p4 然后 p5被推入到队列中  执行p2（2） 执行p5（4）  然后把p6（5）推入到队列中  
            })
            .then(() => { // p1 
                console.log(1)
                new Promise((resolve, reject) => {
                        resolve() //b
                    })
                    .then(() => { // p4
                        console.log(3)
                    })
                    .then(() => { // p5
                        console.log(4)
                    })
                    .then(() => { //p6
                        console.log(5)
                    })
                // console.log(333333)
            })
            .then(() => { // p2
                console.log(2)
            })

        new Promise((resolve, reject) => {
                resolve() //promise2
            })
            .then(() => { // p3
                console.log(7)
            })
        // 宏[]
        // 微[ ]
        // 控制台 111 222 111 444 555 666 777 888 999
        // console.log(111);

        // new Promise((resolve, reject) => {
        //         reject();
        //         // console.log(222);
        //     })
        //     .then(() => {
        //         console.log(333);
        //         return new Promise((resolve) => {
        //             reject();
        //         })
        //     })
        //     .catch(() => {
        //         console.log(444);
        //     })
        //     .then(() => {
        //         console.log(555);
        //         return new Promise((reject, resolve) => {
        //             reject();
        //             // resolve();
        //         });
        //     })
        //     .catch(() => {
        //         console.log(666);
        //         throw new Error("报错了~");
        //     })
        //     .then(() => {
        //         console.log(777);
        //         throw new Error("报错了~");//状态是失败的
        //     })
        //     .then(() => console.log(888))
        //     .then(() => console.log(999))
        //     .catch(() => console.log(101010));

        // console.log(111111);
    </script>
</body>

</html>